apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - netpol_singleuser.yaml
  - netpol_singleuser_world.yaml
  - netpol_auth-proxy_alpine.yaml
  - network_policy.yaml
  - vdi-network-policy.yaml
  - patch-rolebinding.yaml
  - jupyterhub-external-secret.yaml
  - gateway-route.yaml
  - backend-config.yaml
  - auth-proxy-nginx.yaml
  - hub-cluster-role.yaml

patches:
  - path: patch-hub-rolebinding.yaml
    target:
      kind: Job
      name: patch-hub-rolebinding

configMapGenerator:
  - name: jhub-auth-proxy-nginx-template
    namespace: jupyterhub
    files:
      - nginx.conf.template

