apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-guacamole-auth-proxy-to-alpine-repos
  namespace: jupyterhub
spec:
  description: "Allow guacamole auth-proxy access to cluster services and DNS"
  endpointSelector:
    matchLabels:
      app: guacamole-auth-proxy
  egress:
    - toEntities:
        - cluster
