apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager.yaml
  - external-secrets.yaml
  - secret-store.yaml
  - gateway.yaml
  - cnpg.yaml
  - cr8tor.yaml
  - keycloak.yaml
  - backend.yaml
  - jupyterhub.yaml
